/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jbaruch' at '30/12/13 12:59' with Gradle 1.10
 *
 * @author jbaruch, @date 30/12/13 12:59
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
